// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

function optionFromRef(ref) {
  return Caml_option.nullable_to_opt(ref.current);
}

var Dom = 0;

exports.Dom = Dom;
exports.optionFromRef = optionFromRef;
/* No side effect */
