// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var HooksHover$ReasonReactHooks = require("./HooksHover.js");

var useHover = HooksHover$ReasonReactHooks.useHover;

exports.useHover = useHover;
/* HooksHover-ReasonReactHooks Not a pure module */
