// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var UseHover$ReasonReactHooks = require("./hooks/useHover.js");
var UseVisible$ReasonReactHooks = require("./hooks/UseVisible.js");
var UseDebounce$ReasonReactHooks = require("./hooks/UseDebounce.js");
var UseDidMount$ReasonReactHooks = require("./hooks/UseDidMount.js");
var UseWindowSize$ReasonReactHooks = require("./hooks/UseWindowSize.js");

var useHover = UseHover$ReasonReactHooks.useHover;

var useVisible = UseVisible$ReasonReactHooks.useVisible;

var useDebounce = UseDebounce$ReasonReactHooks.useDebounce;

var useWindowSize = UseWindowSize$ReasonReactHooks.useWindowSize;

var useDidMount = UseDidMount$ReasonReactHooks.useDidMount;

exports.useHover = useHover;
exports.useVisible = useVisible;
exports.useDebounce = useDebounce;
exports.useWindowSize = useWindowSize;
exports.useDidMount = useDidMount;
/* UseHover-ReasonReactHooks Not a pure module */
