// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var UseHover$ReasonReactHooks = require("./hooks/useHover.js");

var useHover = UseHover$ReasonReactHooks.useHover;

exports.useHover = useHover;
/* UseHover-ReasonReactHooks Not a pure module */
