// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var HooksHover$ReactHooksTemplate = require("./HooksHover.bs.js");

var useHover = HooksHover$ReactHooksTemplate.useHover;

exports.useHover = useHover;
/* HooksHover-ReactHooksTemplate Not a pure module */
