// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDom = require("react-dom");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function optionFromRef(ref) {
  return Caml_option.nullable_to_opt(ref.current);
}

function useHover(param) {
  var match = React.useState((function () {
          return false;
        }));
  var setIsHovered = match[1];
  var ref = React.useRef(null);
  var onMouseOver = function (param) {
    return Curry._1(setIsHovered, (function (param) {
                  return true;
                }));
  };
  var onMouseOut = function (param) {
    return Curry._1(setIsHovered, (function (param) {
                  return false;
                }));
  };
  React.useEffect((function () {
          Belt_Option.map(Caml_option.nullable_to_opt(ref.current), (function (ref) {
                  var node = ReactDom.findDOMNode(ref);
                  node.addEventListener("mouseenter", onMouseOver);
                  node.addEventListener("mouseleave", onMouseOut);
                  return /* () */0;
                }));
          return (function (param) {
                    Belt_Option.map(Caml_option.nullable_to_opt(ref.current), (function (ref) {
                            var node = ReactDom.findDOMNode(ref);
                            node.removeEventListener("mouseenter", onMouseOver);
                            node.removeEventListener("mouseleave", onMouseOut);
                            return /* () */0;
                          }));
                    return /* () */0;
                  });
        }), /* array */[ref.current]);
  return /* tuple */[
          ref,
          match[0]
        ];
}

exports.optionFromRef = optionFromRef;
exports.useHover = useHover;
/* react Not a pure module */
